# .eslintrc.yaml
---
  extends: 
  env:
    node: true
    mocha: true
    es6: true
    mongo: true
  parser: typescript-eslint-parser
  parserOptions:
    sourceType: module
    ecmaFeatures: 
      modules: true